"""board-threads2

Revision ID: 045640546c20
Revises: 4a3d39e673f7
Create Date: 2016-01-11 16:59:10.456924

"""

# revision identifiers, used by Alembic.
revision = '045640546c20'
down_revision = '4a3d39e673f7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('thread_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message', 'thread', ['thread_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'thread_id')
    ### end Alembic commands ###
