"""bans

Revision ID: 112b62c077f9
Revises: 2ed188326057
Create Date: 2016-01-20 21:42:20.310802

"""

# revision identifiers, used by Alembic.
import sqlalchemy_utils

revision = '112b62c077f9'
down_revision = '2ed188326057'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('end', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ban_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ban_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ban_id'], ['ban.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'message', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'board', ['board_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column(u'message', 'board_id')
    op.drop_table('ban_table')
    op.drop_table('ban')
    ### end Alembic commands ###
