"""board-threads2

Revision ID: 15858ce2abec
Revises: 294752d13996
Create Date: 2016-01-11 16:50:22.845002

"""

# revision identifiers, used by Alembic.
revision = '15858ce2abec'
down_revision = '294752d13996'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
