"""message column

Revision ID: 1b1eec15414f
Revises: 4a34b8c0f0dc
Create Date: 2016-01-11 16:40:26.269704

"""

# revision identifiers, used by Alembic.
revision = '1b1eec15414f'
down_revision = '4a34b8c0f0dc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('messages', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thread', 'message', ['messages'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.drop_column('thread', 'messages')
    ### end Alembic commands ###
