"""thread rm name

Revision ID: 1f5990a4fa45
Revises: 57804253db01
Create Date: 2016-01-11 21:28:59.589878

"""

# revision identifiers, used by Alembic.
revision = '1f5990a4fa45'
down_revision = '57804253db01'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
