"""thread_defaults

Revision ID: 21b151f36d51
Revises: f14327ebb870
Create Date: 2016-01-11 17:44:02.403636

"""

# revision identifiers, used by Alembic.
revision = '21b151f36d51'
down_revision = 'f14327ebb870'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
