"""fix images

Revision ID: 22a96ac72b21
Revises: 8e3ccfa0d388
Create Date: 2016-01-13 23:58:13.954065

"""

# revision identifiers, used by Alembic.
revision = '22a96ac72b21'
down_revision = '8e3ccfa0d388'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
