"""board-threads2

Revision ID: 22d4190d8f6e
Revises: 347414a0b46c
Create Date: 2016-01-11 17:00:26.008425

"""

# revision identifiers, used by Alembic.
revision = '22d4190d8f6e'
down_revision = '347414a0b46c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
