"""empty message

Revision ID: 23a1ca8af5fc
Revises: 563e2d0609d5
Create Date: 2016-01-12 22:20:35.142265

"""

# revision identifiers, used by Alembic.
import sqlalchemy_utils

revision = '23a1ca8af5fc'
down_revision = '563e2d0609d5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('message', sa.UnicodeText(), nullable=False),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('id', 'thread_id')
    )
    op.add_column(u'thread', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'thread', 'board', ['board_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.drop_column(u'thread', 'board_id')
    op.drop_table('message')
    ### end Alembic commands ###
