"""board-threads2

Revision ID: 294752d13996
Revises: 7f552e45e5ad
Create Date: 2016-01-11 16:49:37.148199

"""

# revision identifiers, used by Alembic.
revision = '294752d13996'
down_revision = '7f552e45e5ad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
