"""Section

Revision ID: 2ed188326057
Revises: 715fb3135c3b
Create Date: 2016-01-18 04:42:52.414158

"""

# revision identifiers, used by Alembic.
revision = '2ed188326057'
down_revision = '715fb3135c3b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'board', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board', 'section', ['section_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column(u'board', 'section_id')
    op.drop_table('section')
    ### end Alembic commands ###
