"""thread rm name

Revision ID: 307f97107691
Revises: 87fbd7f8c5f9
Create Date: 2016-01-11 21:17:52.836533

"""

# revision identifiers, used by Alembic.
revision = '307f97107691'
down_revision = '87fbd7f8c5f9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
