"""empty message

Revision ID: 332918486371
Revises: cc62feb16d27
Create Date: 2016-01-11 22:13:07.591427

"""

# revision identifiers, used by Alembic.
revision = '332918486371'
down_revision = 'cc62feb16d27'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
