"""timed

Revision ID: 34478a7af411
Revises: 112b62c077f9
Create Date: 2016-01-23 04:34:25.640021

"""

# revision identifiers, used by Alembic.
revision = '34478a7af411'
down_revision = '112b62c077f9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('available_from', sa.String(), nullable=True))
    op.add_column('board', sa.Column('available_unlil', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'available_unlil')
    op.drop_column('board', 'available_from')
    ### end Alembic commands ###
