"""board-threads2

Revision ID: 347414a0b46c
Revises: 045640546c20
Create Date: 2016-01-11 16:59:42.442484

"""

# revision identifiers, used by Alembic.
revision = '347414a0b46c'
down_revision = '045640546c20'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
