"""thread rm name

Revision ID: 3ca39f591ba8
Revises: 86bfee43cd38
Create Date: 2016-01-11 21:22:35.813513

"""

# revision identifiers, used by Alembic.
revision = '3ca39f591ba8'
down_revision = '86bfee43cd38'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
