"""thread column

Revision ID: 4a34b8c0f0dc
Revises: 9652d4230dc7
Create Date: 2016-01-11 16:39:49.252483

"""

# revision identifiers, used by Alembic.
revision = '4a34b8c0f0dc'
down_revision = '9652d4230dc7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('thread', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'thread', ['thread'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'thread')
    ### end Alembic commands ###
