"""init

Revision ID: 50b23d8a6150
Revises: 
Create Date: 2016-01-12 22:18:02.552267

"""

# revision identifiers, used by Alembic.
import sqlalchemy_utils

revision = '50b23d8a6150'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dir', sa.String(), nullable=False),
    sa.Column('threads_on_page', sa.Integer(), nullable=True),
    sa.Column('default_name', sa.String(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=True),
    sa.Column('thread_bumplimit', sa.Integer(), nullable=True),
    sa.Column('thread_tail', sa.Integer(), nullable=True),
    sa.Column('captcha', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dir'),
    sa.UniqueConstraint('dir'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=False),
    sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType([('adm', u'Admin'),
                              ('mod', u'Moderator'),
                             ]), nullable=False),
    sa.Column('all_boards', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('association',
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('staff')
    op.drop_table('board')
    ### end Alembic commands ###
