"""empty message

Revision ID: 563e2d0609d5
Revises: 50b23d8a6150
Create Date: 2016-01-12 22:19:54.401549

"""

# revision identifiers, used by Alembic.
revision = '563e2d0609d5'
down_revision = '50b23d8a6150'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sticky', sa.BOOLEAN(), nullable=False),
    sa.Column('closed', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread')
    ### end Alembic commands ###
