"""thread rm name

Revision ID: 57804253db01
Revises: 3ca39f591ba8
Create Date: 2016-01-11 21:23:44.488620

"""

# revision identifiers, used by Alembic.
revision = '57804253db01'
down_revision = '3ca39f591ba8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
