"""thread_bump

Revision ID: 58222badb54b
Revises: 921df6955f8f
Create Date: 2016-01-17 05:35:34.037106

"""

# revision identifiers, used by Alembic.
revision = '58222badb54b'
down_revision = '921df6955f8f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('bumped', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'bumped')
    ### end Alembic commands ###
