"""board-threads2

Revision ID: 7029208d2bf6
Revises: 22d4190d8f6e
Create Date: 2016-01-11 17:00:59.987861

"""

# revision identifiers, used by Alembic.
revision = '7029208d2bf6'
down_revision = '22d4190d8f6e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'thread', 'board', ['board_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.drop_column('thread', 'board_id')
    ### end Alembic commands ###
