"""two field deleted

Revision ID: 715fb3135c3b
Revises: 58222badb54b
Create Date: 2016-01-17 23:07:31.290485

"""

# revision identifiers, used by Alembic.
revision = '715fb3135c3b'
down_revision = '58222badb54b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('deleted', sa.BOOLEAN()))
    op.add_column('thread', sa.Column('deleted', sa.BOOLEAN()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'deleted')
    op.drop_column('message', 'deleted')
    ### end Alembic commands ###
