"""board-threads

Revision ID: 7f552e45e5ad
Revises: bea9c7d2bf19
Create Date: 2016-01-11 16:48:21.785001

"""

# revision identifiers, used by Alembic.
revision = '7f552e45e5ad'
down_revision = 'bea9c7d2bf19'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('board_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'thread_board_fkey', 'thread', type_='foreignkey')
    op.create_foreign_key(None, 'thread', 'board', ['board_id'], ['id'])
    op.drop_column('thread', 'board')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('board', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.create_foreign_key(u'thread_board_fkey', 'thread', 'board', ['board'], ['id'])
    op.drop_column('thread', 'board_id')
    ### end Alembic commands ###
