"""email

Revision ID: 7fc3eea2774b
Revises: 4fb6b6488929
Create Date: 2016-01-29 16:51:12.694530

"""

# revision identifiers, used by Alembic.
import random
import string

import sqlalchemy_utils

revision = '7fc3eea2774b'
down_revision = '4fb6b6488929'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True))
    op.create_unique_constraint(None, 'staff', ['email'])
    op.alter_column('thread', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    conn = op.get_bind()
    # a = lambda: ''.join(random.choice(string.ascii_lowercase) for x in range(6))
    #
    # conn.execute(text("""UPDATE staff SET email='%s@ech.su'""" %
    #                   (a())))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thread', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'email')
    ### end Alembic commands ###
