"""thread rm name

Revision ID: 83858e3536e4
Revises: 1f5990a4fa45
Create Date: 2016-01-11 21:30:55.482397

"""

# revision identifiers, used by Alembic.
revision = '83858e3536e4'
down_revision = '1f5990a4fa45'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
