"""thread rm name

Revision ID: 86bfee43cd38
Revises: 307f97107691
Create Date: 2016-01-11 21:21:28.361047

"""

# revision identifiers, used by Alembic.
revision = '86bfee43cd38'
down_revision = '307f97107691'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
