"""thread rm name

Revision ID: 87fbd7f8c5f9
Revises: 21b151f36d51
Create Date: 2016-01-11 19:09:59.323386

"""

# revision identifiers, used by Alembic.
revision = '87fbd7f8c5f9'
down_revision = '21b151f36d51'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
