"""message_create_at

Revision ID: 921df6955f8f
Revises: d962c7d0642e
Create Date: 2016-01-17 04:09:03.041933

"""

# revision identifiers, used by Alembic.
import sqlalchemy_utils

revision = '921df6955f8f'
down_revision = 'd962c7d0642e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('datetime', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'datetime')
    ### end Alembic commands ###
