"""init

Revision ID: ab37199b9b0d
Revises: e033a5061e67
Create Date: 2016-01-11 16:06:55.076483

"""

# revision identifiers, used by Alembic.
import sqlalchemy_utils

revision = 'ab37199b9b0d'
down_revision = 'e033a5061e67'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy_defaults import Column


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    Column('id', sa.Integer(), nullable=False),
    Column('name', sa.String(), nullable=False),
    Column('dir', sa.String(), nullable=False),
    Column('threads_on_page', sa.Integer(), nullable=True),
    Column('default_name', sa.String(), nullable=False),
    Column('max_pages', sa.Integer(), nullable=True),
    Column('thread_bumplimit', sa.Integer(), nullable=True),
    Column('captcha', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dir'),
    sa.UniqueConstraint('dir'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('message',
    Column('id', sa.Integer(), nullable=False),
    Column('poster_name', sa.String(), nullable=False),
    Column('email', sa.String(), nullable=False),
    Column('header', sa.String(), nullable=False),
    Column('message', sa.UnicodeText(), nullable=False),
    Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=True),
    Column('ip_address', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    Column('id', sa.Integer(), nullable=False),
    Column('name', sa.String(), nullable=False),
    Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=False),
    Column('role', sqlalchemy_utils.types.choice.ChoiceType(
            [('adm', u'Admin'),
             ('mod', u'Moderator'),
            ]), nullable=False),
    Column('all_boards', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('thread',
    Column('id', sa.Integer(), nullable=False),
    Column('name', sa.String(), nullable=False),
    Column('sticky', sa.BOOLEAN(), nullable=False),
    Column('closed', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    Column('staff_id', sa.Integer(), nullable=True),
    Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('thread')
    op.drop_table('staff')
    op.drop_table('message')
    op.drop_table('board')
    ### end Alembic commands ###
