"""empty message

Revision ID: b76e2309cad5
Revises: ec60e713c3ab
Create Date: 2016-01-12 01:24:29.995751

"""

# revision identifiers, used by Alembic.
revision = 'b76e2309cad5'
down_revision = 'ec60e713c3ab'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
