"""board

Revision ID: bea9c7d2bf19
Revises: 8f0588ea23fe
Create Date: 2016-01-11 16:44:28.412800

"""

# revision identifiers, used by Alembic.
revision = 'bea9c7d2bf19'
down_revision = '8f0588ea23fe'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('board', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'thread', 'board', ['board'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.drop_column('thread', 'board')
    ### end Alembic commands ###
