"""two field deleted

Revision ID: c69d2601a400
Revises: 48127c4db6f5
Create Date: 2016-01-17 22:40:50.295040

"""

# revision identifiers, used by Alembic.
revision = 'c69d2601a400'
down_revision = '48127c4db6f5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('deleted', sa.BOOLEAN()))
    op.add_column('thread', sa.Column('deleted', sa.BOOLEAN()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'deleted')
    op.drop_column('message', 'deleted')
    ### end Alembic commands ###
