"""thread rm name

Revision ID: cc62feb16d27
Revises: 83858e3536e4
Create Date: 2016-01-11 21:32:53.836195

"""

# revision identifiers, used by Alembic.
revision = 'cc62feb16d27'
down_revision = '83858e3536e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
