"""empty message

Revision ID: d962c7d0642e
Revises: 1333dda789bf
Create Date: 2016-01-17 02:37:22.234625

"""

# revision identifiers, used by Alembic.
revision = 'd962c7d0642e'
down_revision = '1333dda789bf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###
