"""board-threads2

Revision ID: dfcf62aaa482
Revises: 15858ce2abec
Create Date: 2016-01-11 16:54:19.868662

"""

# revision identifiers, used by Alembic.
revision = 'dfcf62aaa482'
down_revision = '15858ce2abec'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
