"""empty message

Revision ID: e033a5061e67
Revises: 
Create Date: 2016-01-11 15:58:36.566243

"""

# revision identifiers, used by Alembic.
revision = 'e033a5061e67'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
