"""empty message

Revision ID: ec60e713c3ab
Revises: 332918486371
Create Date: 2016-01-11 22:37:50.685393

"""

# revision identifiers, used by Alembic.
revision = 'ec60e713c3ab'
down_revision = '332918486371'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('thread_tail', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'thread_tail')
    ### end Alembic commands ###
