"""board-threads2

Revision ID: f14327ebb870
Revises: 7029208d2bf6
Create Date: 2016-01-11 17:02:12.645612

"""

# revision identifiers, used by Alembic.
revision = 'f14327ebb870'
down_revision = '7029208d2bf6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
