"""nullable columns

Revision ID: fd698d708871
Revises: 37518e414d8e
Create Date: 2016-01-12 16:02:20.696288

"""

# revision identifiers, used by Alembic.
revision = 'fd698d708871'
down_revision = '37518e414d8e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('message', 'header',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('message', 'poster_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'poster_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('message', 'header',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('message', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
